package:
  name: darts_dnn
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python=2.7
    - keras
    - numpy
    - pyyaml
    - h5py
    - scikit-learn
    - scipy
    - tqdm>=4.14
    - pandas>=0.21.0
    - theano
  run:
    - python=2.7


test:
  imports:
    - Darts_DNN