v0.0.1:
  SE: ~/.darts/trainedParam/encode_plus_roadmap/best_testing_model.h5


v0.1.0:
  SE: ~/.darts/v0.1.0/trainedParam/SE.h5
  A5SS: ~/.darts/v0.1.0/trainedParam/A5SS.h5
  A3SS: ~/.darts/v0.1.0/trainedParam/A3SS.h5
  RI: ~/.darts/v0.1.0/trainedParam/RI.h5
